# Generated by Django 5.1.4 on 2025-01-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video')], default='document', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
